### ISSUE TITLE
.env || key is visible

### ISSUE THREAD

**Issue by withrvr** [Idris110/Github-finder#2]
# solution
- add .env in `.gitignore` file
- like this `.env*` .... so it will work for all .env files

# error
- if this key has all type of access
- if anyone finds out or uses it
- you are fked .. 
  - this is small project but if large
  - your GitHub is fked /// or your project on which you working
  - because then they have access to that project database ... like here your GitHub account
![image](https://user-images.githubusercontent.com/69628500/214228274-42b39e96-4db2-4783-8ec3-84bcb3bf122d.png)

**Comment by Idris110** [comment]
key has been hidden using .env
